version: '3.4'

services:
  pvapi:
    image: pvapi
    build:
      context: pv_process_api
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
